In [1]:
import torch

In [3]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

In [4]:
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [5]:
x = torch.arange(4)

In [6]:
x

tensor([0, 1, 2, 3])

In [7]:
x[3]

tensor(3)

In [9]:
len(x)

4

In [10]:
x.shape

torch.Size([4])

In [11]:
A = torch.arange(20).reshape(5,4)

In [12]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [13]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [14]:
A


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])