In [1]:
import torch

In [3]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

In [4]:
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [5]:
x = torch.arange(4)

In [6]:
x

tensor([0, 1, 2, 3])

In [7]:
x[3]

tensor(3)

In [9]:
len(x)

4

In [10]:
x.shape

torch.Size([4])

In [11]:
A = torch.arange(20).reshape(5,4)

In [12]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [13]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [15]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])

In [16]:
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [17]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [18]:
X = torch.arange(24).reshape(2,3,4)

In [19]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [22]:
# 给定具有相同形状的任何两个张量，任何按照元素二元运算的结果都将是相同形状的张量
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B

In [23]:
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [25]:
A, B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [26]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [37]:
a = 2
X = torch.arange(20*2).reshape(2,5,4)

In [44]:
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13],
          [14, 15, 16, 17],
          [18, 19, 20, 21]],
 
         [[22, 23, 24, 25],
          [26, 27, 28, 29],
          [30, 31, 32, 33],
          [34, 35, 36, 37],
          [38, 39, 40, 41]]]),
 torch.Size([2, 5, 4]))

In [39]:
x = torch.arange(4, dtype=torch.float32)

In [40]:
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [41]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

In [64]:
A = torch.arange(20*2, dtype=torch.float32).reshape(2, 5, 4)

In [65]:
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [66]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [67]:
# 指定求和汇总张量的轴
A_sum_axis0 = A.sum(axis=0)

In [68]:
A_sum_axis0, A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [69]:
A_sum_axis1 = A.sum(axis=1)

In [70]:
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [71]:
A_sum_axis2 = A.sum(axis=2)

In [72]:
A_sum_axis2, A_sum_axis2.shape

(tensor([[  6.,  22.,  38.,  54.,  70.],
         [ 86., 102., 118., 134., 150.]]),
 torch.Size([2, 5]))

In [73]:
A.sum(axis=[0, 1])

tensor([180., 190., 200., 210.])

In [74]:
A.sum(axis=[0, 1]).shape

torch.Size([4])

In [75]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [82]:
A.numel()

40

In [83]:
A.sum()

tensor(780.)

In [78]:
A.mean(),A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [79]:
A.shape

torch.Size([2, 5, 4])

In [81]:
A.shape[0]

2

In [84]:
A.sum(axis=0)

tensor([[20., 22., 24., 26.],
        [28., 30., 32., 34.],
        [36., 38., 40., 42.],
        [44., 46., 48., 50.],
        [52., 54., 56., 58.]])

In [85]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

In [90]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [91]:
A.shape

torch.Size([2, 5, 4])

In [88]:
# 计算总和或均值时保持轴数不变
sum_A = A.sum(axis=1, keepdims=True)

In [89]:
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [92]:
sum_A.shape

torch.Size([2, 1, 4])

In [93]:
A/sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [94]:
# 某个轴计算A元素的累积总和
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [95]:
x

tensor([0., 1., 2., 3.])

In [96]:
y = torch.ones(4,dtype=torch.float32)

In [97]:
y

tensor([1., 1., 1., 1.])

In [99]:
# 点积
torch.dot(x,y)

tensor(6.)

In [100]:
# 可以通过执行按元素乘法，然后进行求和来表示两个向量的点积
torch.sum(x*y)

tensor(6.)

In [101]:
A.shape

torch.Size([2, 5, 4])

In [104]:
C = torch.arange(20,dtype=torch.float32).reshape(5,4)

In [105]:
C

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [106]:
C.shape

torch.Size([5, 4])

In [110]:
x

tensor([0., 1., 2., 3.])

In [107]:
x.shape

torch.Size([4])

In [109]:
# 矩阵Cx是一个长度为m的列向量，其i(上标th)元素是点积c(上标T，下标i)x
torch.mv(C,x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [111]:
D = torch.ones(4,3)

In [112]:
D

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [114]:
D.shape

torch.Size([4, 3])

In [115]:
C.shape

torch.Size([5, 4])

In [113]:
# 可以将矩阵-矩阵的乘法CD，看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个nxm矩阵
torch.mm(C,D)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [118]:
# L2范数是向量元素平方和的平方根
u = torch.tensor([3.0, -4.0])

In [119]:
torch.norm(u)

tensor(5.)

In [121]:
torch.abs(u)

tensor([3., 4.])

In [120]:
# L1范数表示为向量元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [122]:
# 矩阵的弗罗贝尼乌斯范数(Frobenius norm)是矩阵元素的平方和的平方根
torch.norm(torch.ones((4,9)))

tensor(6.)