In [1]:
import torch

In [2]:
a = torch.ones((2,5,4))

In [6]:
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [3]:
a.shape

torch.Size([2, 5, 4])

In [5]:
a.sum().shape # shape为空，说明这是一个标量

torch.Size([])

In [7]:
a.sum(axis=1)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [8]:
a.sum(axis=1).shape

torch.Size([2, 4])

In [9]:
a.sum(axis=0)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [10]:
a.sum(axis=0).shape

torch.Size([5, 4])

In [11]:
a.sum(axis=[0,2])

tensor([8., 8., 8., 8., 8.])

In [12]:
a.sum(axis=[0,2]).shape

torch.Size([5])

In [13]:
a.sum(axis=1,keepdim=True)

tensor([[[5., 5., 5., 5.]],

        [[5., 5., 5., 5.]]])

In [14]:
a.sum(axis=1,keepdim=True).shape

torch.Size([2, 1, 4])

In [15]:
a.sum(axis=[0,2],keepdim=True)

tensor([[[8.],
         [8.],
         [8.],
         [8.],
         [8.]]])

In [16]:
a.sum(axis=[0,2],keepdim=True).shape

torch.Size([1, 5, 1])